package model;

public enum OrderEvent {
    ADD_SANDWICH,
    DELETE_SANDWICH,
    ADD_IDENTICAL_SANDWICH,
    Add_TOPPING,
    CANCEL_ORDER,
    TERMINATE_ORDER,
    PAY_ORDER,
    ORDER_TO_KITCHEN,
    START_PREPARATION,
    ORDER_IS_DONE,
}
