package model;

public enum OrderEvents {
    TOEVOEGEN_BROODJE,
    VERWIJDER_BROODJE,
    TOEVOEGEN_IDENTIEK_BROODJE,
    TOEVOEGEN_BELEG,
    BESTELLING_ANNULEREN,
    BESTELLING_AFGESLOTEN,
    BESTELLING_BETALEN,
    BESTELLING_NAAR_KEUKEN,
    START_BEREIDING,
    BESTELLING_AFGEWERKT

}
