package model;

public enum OrderEvent {
    ADD_SANDWICH,
    VERWIJDER_BROODJE,
    TOEVOEGEN_IDENTIEK_BROODJE,
    TOEVOEGEN_BELEG,
    BESTELLING_ANNULEREN,
    BESTELLING_AFGESLOTEN,
    BESTELLING_BETALEN,
    BESTELLING_NAAR_KEUKEN,
    START_BEREIDING,
    BESTELLING_AFGEWERKT

}
